# Generated by Django 4.0.2 on 2022-02-26 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='School_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=5)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_class', to='api_app.school')),
            ],
        ),
        migrations.CreateModel(
            name='Class_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=5)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_section', to='api_app.school_class')),
            ],
        ),
    ]
